### ISSUE TITLE
Migrate GirdView to RecyclerView

### ISSUE THREAD

**Issue by VerachadW** [prisa1987/ShowTimeDemo#20]
https://github.com/prisa1987/ShowTimeDemo/blob/2f8f284d0267848059b03319f921d0b23680da3e/app/src/main/res/layout/activity_watchlist.xml#L8

I'm not sure you had read about RecyclerView or not, but Google has introduce this since the Lolipop came out to replace the old-fashioned ListView/GridView. So, please move to use this new widget. You can see some example [here](http://blog.sqisland.com/2014/12/recyclerview-grid-with-header.html). 

PS. Ignore the header section in the example link

**Comment by prisa1987** [comment]
Move to use recycler view
