### ISSUE TITLE
Usage of Thread Policy

### ISSUE THREAD

**Issue by kittinunf** [prisa1987/ShowTimeDemo#4]
Whenever, I see usage of Thread Policy, there must be a really good reason for it. 

https://github.com/prisa1987/ShowTimeDemo/blob/master/app/src/main/kotlin/com/showtime/prisa/showtimedemo/Presentation/View/MainActivity.kt#L35-36

I am still unsure why you do this, please explain.

**Comment by prisa1987** [comment]
I use HTTPClient,HTTPRequest  then it's not allow to use UI Thread.

**Comment by kittinunv-taskworld** [comment]
This is a sign of bad design. ```HTTPClient``` should belong to background thread only and no need to set policy in ```Activity```, or ```Fragment```

**Comment by prisa1987** [comment]
Ok, I will improve it :)   Thank you so much

**Comment by prisa1987** [comment]
I improve it using call back retrofit.
